### ISSUE TITLE
Modify URDF path of MoveIt! Setup Assistant

### ISSUE THREAD

**Issue by mgvargas** [mgvargas/Moveit_config#5]
Modify URDF path of MoveIt! Setup Assistant, since URDF folder was deleted from this repo- Use the one in iai_robots

**Comment by chainedcoder** [comment]
i dont see an iai_robots folder/file

**Comment by mgvargas** [comment]
It is in  [https://github.com/code-iai/iai_robots](url),  inside the iai_boxy_description
